# Basic
title: 渐寒
subtitle: Welcome~
description: 世界很大，多去看看
# 头像里面的标题
avatarTitle: Fleschier
# 头像里面的描述
avatarDesc:
url: "https://Fleschier.github.io"


# Social
social:
    github: Fleschier
    # twitter:
    mail: fleschierchan@gmail.com

# 百度统计
#baidu:
    #id: 8ba1c6be0953b6f9c2ba38e57f615421

# Google Analytics
#ga:
    #id: UA-84134159-3
    #host: auto

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #0000

#this is the color for the home page background
# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 主页

# Navigation buttons in the front page.s
nav:
    - {title: 文章, description: archive, url: '/archive'}
    - {title: 归档, description: tags, url: '/tags'}
    - {title: 关于, description: about, url: '/about'}

# Featured Tags
featured-tags: true                   # whether or not using Feature-Tags
featured-condition-size: 0            # A tag will be featured if the size of it is more than this condition value

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 8
paginate_path: "page/:num/"

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
